resources:
  jobs:
    Transactions:
      name: Transactions
      tasks:
        - task_key: Ingest_Customers
          notebook_task:
            notebook_path: examples/databricks/transactions/bronze/nb_ingest_raw_customers
            source: GIT
          job_cluster_key: Job_cluster
        - task_key: Ingest_Transactions
          notebook_task:
            notebook_path: examples/databricks/transactions/bronze/nb_ingest_raw_transactions
            source: GIT
          job_cluster_key: Job_cluster
        - task_key: Clean_Transactions
          depends_on:
            - task_key: Ingest_Transactions
          notebook_task:
            notebook_path: examples/databricks/transactions/silver/nb_clean_transactions
            source: GIT
          job_cluster_key: Job_cluster
        - task_key: Customer_Summary
          depends_on:
            - task_key: Ingest_Customers
            - task_key: Clean_Transactions
          notebook_task:
            notebook_path: examples/databricks/transactions/silver/nb_create_customer_summary
            source: GIT
          job_cluster_key: Job_cluster
      job_clusters:
        - job_cluster_key: Job_cluster
          new_cluster:
            spark_version: 16.4.x-scala2.12
            azure_attributes:
              first_on_demand: 1
              availability: SPOT_WITH_FALLBACK_AZURE
              spot_bid_max_price: -1
            node_type_id: Standard_D4ds_v5
            spark_env_vars:
              PYSPARK_PYTHON: /databricks/python3/bin/python3
            enable_elastic_disk: true
            data_security_mode: LEGACY_SINGLE_USER_STANDARD
            runtime_engine: STANDARD
            kind: CLASSIC_PREVIEW
            is_single_node: false
            num_workers: 1
      git_source:
        git_url: https://github.com/GiorgosPa/jorvik
        git_provider: gitHub
        git_branch: examples
      queue:
        enabled: true
