# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 jorvik --count --max-line-length=127 --ignore=E302,E305 --statistics
    - name: Install cspell
      run: npm install cspell
    - name: Spell check code
      run: |
        npx cspell lint jorvik --quiet
    - name: Install package
      run: |
          python -m pip install --upgrade pip
          pip install pytest-cov
          pip install -e '.[tests]'
    - name: Run tests
      run: |
        pytest --cov=. test --cov-report=xml
