name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install twine
    - name: Build package
      run: |
        echo __version__ = '"${{ github.event.release.tag_name }}"' > jorvik/version.py
        python -m build
    - name: Publish package
      run: |
        twine upload --username ${{ secrets.pypi_api_username}} --password ${{ secrets.pypi_api_token }} --verbose --skip-existing dist/*.whl
